### ISSUE TITLE
How to display 1 toot only rather than all conversation toots

### ISSUE THREAD

**Issue by itsumonotakumi** [ginsterbusch/mastodon-embed#2]
Can this plugin display 1 toot only instead of all conversation toots?
e.g. [mastodon no_iframe="1"]https://mstdn.jp/@omimi/4249103[/mastodon]

If you know this, please know me how to display it.

**Comment by ginsterbusch** [comment]
Sorry, your question somehow went under.

I'm currently looking into it. Just the starting toot of a conversation, or specifically picking out a single toot from the conversation?

The first should work (might just add a "limit_toots" or similary named parameter), but the latter .. I don't know.

cu, w0lf.

**Comment by ginsterbusch** [comment]
Guess I figured it out. Gonna implement it with a parameter called `center`, which is enabled by default :)

cu, w0lf.

**Comment by ginsterbusch** [comment]
Ok, it's implemented. Get the latest release now! :)

cu, w0lf.

**Comment by itsumonotakumi** [comment]
Thank you for nice implementation!
I use it and will introduce it to Japanese users by my blog.

Thanks,
itsumonotakumi
