### ISSUE TITLE
"center" switch cannot be enabled

### ISSUE THREAD

**Issue by itsumonotakumi** [ginsterbusch/mastodon-embed#3]
Hi, this plugin's "center" switch cannot be enabled. I try it by next sentence.

1) [mastodon]https://pawoo.net/@itsumonotakumi/12846343[/mastodon]
2) [mastodon center="0"]https://pawoo.net/@itsumonotakumi/12846343[/mastodon]

These sentences are displayed the same screen.
Please check it.

**Comment by ginsterbusch** [comment]
Because of possible issues with older PHP releases, and apparent different implementations of the empty() function, I've changed the "center" attribute to "no_center".

Please note: The center function ONLY works with direct embedding a toot, ie. usage of `no_iframe=1`.

Example:

```
[mastodon no_center="1" no_iframe="1"]https://pawoo.net/@itsumonotakumi/12846343[/mastodon]
```

**Comment by itsumonotakumi** [comment]
Thank you for your quick improvement.
I could check this, and I will intoduce this to Japanese users in these pages.

https://takulog.info/mastodon-embed-2-4/

and this page:

https://takulog.info/mastodon-embed-wordpress-plugin/

Sorry for Japanese only..
