### ISSUE TITLE
Show an user page and not just a toot

### ISSUE THREAD

**Issue by ghost** [ginsterbusch/mastodon-embed#6]
Hi !
Is it possible to add an option to display an user page and not just one toot ?
I mean that if I toot something new, it will be shown automatically without me having to create a new shortcode for it.

Thank :)

**Comment by ginsterbusch** [comment]
No .. thats kind of a total different function. What you're proposing or searching for, is essentially embedding the timeline of a user, while the sole purpose of Mastodon Embed Improved is to let one easily embed a single toot or its whole thread - if publicy accessible - into a WP post or page.

That would be some kind of plugin, able to access the Mastodon API directly, and fetching the given user timeline every time there is a change or when someone accesses the page its being embedded in.

To conclude my answer: I might be looking into this when I got some time to spare, but cannot make any promises, sorry.

cu, w0lf.

**Comment by ghost** [comment]
No problem, thanks for the quick answer !

**Comment by Yeru-314** [comment]
+1 to that. Would be very appreciated :)
