### ISSUE TITLE
Limit number of feed items

### ISSUE THREAD

**Issue by 22nds** [ginsterbusch/mastodon-embed#8]
I am wondering if there is any way I could limit the number of included items in the feed. Right now all of them are showing and the plugin is taking too much vertical space. 

Example: https://www.lezfemuniverza.org/

Thanks for any suggestions!

**Comment by ginsterbusch** [comment]
I never thought of this, but one could probably add a "limit" or "limit_entries" option, which would count the number of `.entry` appearances and cut them off (or more like, just extract this number) after the given number.

I'm going to look into this and might do an update soon :)
It looks like a rather easy thing to achieve, with something on the lines of searching for anything `.entry` contained in the activity-stream content, and then just cycling through it.

cu, w0lf.

**Comment by ginsterbusch** [comment]
Untested code, which has to be inserted after `$embed_content = $dom->find( '.activity-stream', 0 );`

```
$limit_entries = 10; // workaround for now, as this shortcode attribute does not yet exist!

if( !empty( $limit_entries ) && $limit_entries >= 1 ) {
	$_embed_content = $embed_content; // backup original
	
	foreach( $embed_content->find( '.entry' ) as $entry_count => $entry_item ) {
		if( $entry_count >= $limit_entries ) {
			$entry_item->outertext = '';
		}
	}
}
```

**Comment by 22nds** [comment]
@ginsterbusch This works perfectly! Thanks a lot for such fast solution :) And I am looking forward to new options in the next releases.
