### ISSUE TITLE
iframe height 1000px

### ISSUE THREAD

**Issue by quicoto** [ginsterbusch/mastodon-embed#9]
Plugin version 2.5
WordPress version 4.9.8

For some reason the iframe is way to tall, 1000px

Am I missing something? I just activated the plugin and pasted a toot URL 

`https://mastodon.social/@ricard_dev/100691966805375213`

![iframe](https://cldup.com/pPfGF1rFVF.png)

Thank you.

**Comment by ginsterbusch** [comment]
Strange. This doesnt really look like code from the plugin. Is there some other plugin, which embeds URLs, possibly interfering here?

**Comment by quicoto** [comment]
Yeah tried deactivating the plugins, it must be the theme or some JS from the theme.

I'm using https://wordpress.org/themes/atomic-blocks/

Thank you anyway
